apiVersion: cert-manager.io/v1
# https://cert-manager.io/docs/configuration/
# Cluster Issuer represent certificate authorities
# CAs are able to sign certs in response to certificate signing requests
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
# https://cert-manager.io/docs/usage/certificate/
# Certificate represents human readable definition of a certificate requests
# cert-manager generates with this a private key and CertificateRequest Resource
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-secret

