apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
#    This is commented since we have the console as separate item below
#    - name: management-console
#      expose: true
#      port: 8161
#      protocols: all
#      sslEnabled: false
    - name: amqp
      protocols: amqp
      port: 5672
      connectionsAllowed: 5
  console:
    expose: true
    name: webconsole
    sslEnabled: False
  adminUser: postgres
  adminPassword: postgres
