apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  # version: 2.32.0
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    # messageMigration requires 2+ brokers
    messageMigration: true
