apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-springcloud
spec:
  deploymentPlan:
    size: 3
    messageMigration: true
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "250m"
        memory: "512Mi"
  acceptors:
    - name: amqp
      protocols: amqp
      port: 5672
      connectionsAllowed: 5
  # Expose the management console
  console:
    expose: true

