apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  # version: 2.32.0
  acceptors:
#    This is commented since we have the console as separate item below
#    - name: management-console
#      expose: true
#      port: 8161
#      protocols: all
#      sslEnabled: false
    # see artemis_springcloud.yaml
    # Todo - maybe it's better to limit the acceptor not to include all protocols -> exclude all not necessary protocols
#    - name: amqp
#      protocols: amqp
#      port: 5672
#      connectionsAllowed: 5
    # See also file: artemis_ssl_acceptor_cert_and_trust_managers.yaml
    # See file: broker_activemqartemis_cr.yaml
    - name: anevis-acceptor-all
      protocols: all
      port: 61616
      sslEnabled: false
      # Enabled protocols is a TLS configuration - we have no TLS here
      # enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: false
      wantClientAuth: false
      verifyHost: false
      exposeMode: ingress
      ingressHost: asdf.asdf
      expose: True
  console:
      expose: true
      name: webconsole
      # exposeMode and ingressHost are required for exposing the console!
      exposeMode: ingress
      ingressHost: asdf.asdf
      sslEnabled: false
  adminUser: admin
  adminPassword: admin
