apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
    - name: management-console
      expose: true
      port: 8161
      protocols: all
      sslEnabled: false

