apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
#    This is commented since we have the console as separate item below
#    - name: management-console
#      expose: true
#      port: 8161
#      protocols: all
#      sslEnabled: false
    # see artemis_springcloud.yaml
    - name: amqp
      protocols: amqp
      port: 5672
      connectionsAllowed: 5
    # See also file: artemis_ssl_acceptor_cert_and_trust_managers.yaml
    - name: test
      protocols: all
      port: 61616
      sslEnabled: false
      expose: True
  console:
    expose: true
    name: webconsole
    sslEnabled: False
  adminUser: postgres
  adminPassword: postgres
