# See: https://artemiscloud.io/docs/tutorials/ssl_broker_setup/
# The deployment Plan sections needs to disabled as this was written when the whole project was in alpha stage
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
    - name: sslacceptor-all
      protocols: all
      port: 61616
      expose: true
      sslEnabled: true
      # sslSecret: ex-aao-sslacceptor-secret
      # verifyHost: false
  console:
      expose: true
      name: webconsole
      sslEnabled: false
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
