# See: https://artemiscloud.io/docs/tutorials/ssl_broker_setup/
# The deployment Plan sections needs to disabled as this was written when the whole project was in alpha stage
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  # acceptors:
  #   - name: sslacceptor
  #     protocols: all
  #     port: 61617
  #     sslEnabled: true
  acceptors:
    - name: sslacceptor-all
      protocols: all
      port: 61616
      sslEnabled: true
      sslSecret: ex-aao-sslacceptor-secret
      # enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      # needClientAuth: false
      # wantClientAuth: false
      # verifyHost: false
      # expose: True
  console:
      expose: true
      name: webconsole
      sslEnabled: false
      # sslSecret: ex-aao-sslacceptor-secret
  adminUser: postgres
  adminPassword: postgres