# See: https://artemiscloud.io/docs/tutorials/ssl_broker_setup/
# The deployment Plan sections needs to disabled as this was written when the whole project was in alpha stage
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
    - name: sslacceptor
      protocols: all
      port: 61616
      expose: true
      sslEnabled: true
      sslSecret: artemis-broker-sslacceptor-secret
      # default false for acceptors
      verifyHost: false
  console:
      # webconsole is normally in port 8161
      expose: true
      name: webconsole
      sslEnabled: false
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
