# EKS Cluster Configuration file
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
- ${AWS_REGION}a
- ${AWS_REGION}b
- ${AWS_REGION}c

metadata:
  name: ${EKS_CLUSTER_NAME}
  region: ${AWS_REGION}
  version: '1.29'
  tags:
    karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
    created-by: anevis-solutions
    env: ${EKS_CLUSTER_NAME}

# Enables OpenID Connect
# = interoperable authentication framework
# Removes the responsibility of setting, storing and managing passwords, with OpenID Provider
# Widely adopted by identity providers over the internet
iam:
  withOIDC: true

vpc:
  cidr: 10.42.0.0/16
  # = accessibility of the Kubernetes API server
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
  # CNI = Container Network Interface
  # VPC-NVI is a kubernetes networking plugin used in eks 
  # Jobs: Allocating VPC Ip addresses to k8s nodes, configuring the networking for each pod on each node
- name: vpc-cni
  version: 1.14.1
  # vpc-cni is also a requirement for the AWS NLB https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/
  # ENABLE_PREFIX_DELEGATION = assign multiple IP addresses from a large IP address block to a network interface
  # ENABLE_POD_ENI = enables Pod Elastic Network Interface, allows to assign ENI to a Pod for network traffic isolution
  # POD_SECURITY_GROU_ENFORCING_MODE = standard = security group specified in the pod annotation withh be enforced
  # enableNetworkPolicy = allows to control traffic flow at IP address and Poert level
  configurationValues:  "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"},\"enableNetworkPolicy\": \"true\"}"
  # This config overwrites any previous config
  resolveConflicts: overwrite

managedNodeGroups:
- name: default
  desiredCapacity: 3
  minSize: 3
  maxSize: 6
  ### Overview of the instances with their respective assumed costs
  ### T3 Instances (Burstable Performance)
  # | Instance Type | vCPUs | Memory (GB) | On-Demand Price (per hour, USD) |
  # |---------------|-------|-------------|---------------------------------|
  # | t3.nano       | 2     | 0.5         | $0.0052                         |
  # | t3.micro      | 2     | 1           | $0.0104                         |
  # | t3.small      | 2     | 2           | $0.0208                         |
  # | t3.medium     | 2     | 4           | $0.0416                         |
  # | t3.large      | 2     | 8           | $0.0832                         |
  # | t3.xlarge     | 4     | 16          | $0.1664                         |
  # | t3.2xlarge    | 8     | 32          | $0.3328                         |

  ### M5 Instances (Balance of Compute, Memory, Networking)
  # | Instance Type | vCPUs | Memory (GB) | On-Demand Price (per hour, USD) |
  # |---------------|-------|-------------|---------------------------------|
  # | m5.large      | 2     | 8           | $0.096                          |
  # | m5.xlarge     | 4     | 16          | $0.192                          |
  # | m5.2xlarge    | 8     | 32          | $0.384                          |
  # | m5.4xlarge    | 16    | 64          | $0.768                          |
  # | m5.12xlarge   | 48    | 192         | $2.304                          |
  # | m5.24xlarge   | 96    | 384         | $4.608                          |
  # | m5.metal      | 96    | 384         | $4.608                          |
  # instanceType: m5.large # This was the default for the eksworkshop, it also works for the artemis operator
  # instanceType: t2.micro
  # instanceType: t3.micro # -> This led to this error: Warning  Unsupported  2m40s (x22 over 67m)  vpc-resource-controller  The instance type t3.micro is not supported for trunk interface (Security Group for Pods)
  # instanceType: t3.nano # -> kubectl get deployment -A -> coredns was not available as well as aws-load-balancer-controller after installation
  instanceType: t3.small
  # Originally this was set to true
  # Reference found with this video: https://www.youtube.com/watch?v=a4qdvu5cVIU
  # And via querying in bing chat.
  privateNetworking: false
  # This version is out of date: Documentation: If you don't specify a version, the template's default version is used
  # releaseVersion: 1.27.3-20230816
  updateConfig:
    # maximum percentage of nodes that can be unavailable during an update
    maxUnavailablePercentage: 50
  # -------------------------------------------
  # Removed from eksworkshop config
  # the kubernetes labels to be applied to the nodes in the node group
  # labels:
  #   workshop-default: 'yes'
  # -------------------------------------------
  iam:
    withAddonPolicies:
      # See this: https://github.com/kubernetes-sigs/external-dns
      # This is not required, it was just interesting to experiment with this
      externalDNS: true
      certManager: true
      # Replaces the following commands (during setup, see nodes):
      # `curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.4/docs/install/iam_policy.json`
      # `aws iam create-policy \
      #       --policy-name AWSLoadBalancerControllerIAMPolicy \
      #       --policy-document file://iam_policy.json`
      # This does not work for some reason - https://eksctl.io/usage/iam-policies/
      # No Idea why :(
      awsLoadBalancerController: true
