# EKS Cluster Configuration file
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
- ${AWS_REGION}a
- ${AWS_REGION}b
- ${AWS_REGION}c

metadata:
  name: ${EKS_CLUSTER_NAME}
  region: ${AWS_REGION}
  version: '1.27'
  tags:
    karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
    created-by: anevis-solutions
    env: ${EKS_CLUSTER_NAME}

# Enables OpenID Connect
# = interoperable authentication framework
# Removes the responsibility of setting, storing and managing passwords, with OpenID Provider
# Widely adopted by identity providers over the internet
iam:
  withOIDC: true

vpc:
  cidr: 10.42.0.0/16
  # = accessibility of the Kubernetes API server
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
  # CNI = Container Network Interface
  # VPC-NVI is a kubernetes networking plugin used in eks 
  # Jobs: Allocating VPC Ip addresses to k8s nodes, configuring the networking for each pod on each node
- name: vpc-cni
  version: 1.14.1
  # Todo I don't know how this vpc-cni vonfiguration values affect the cluster
  # vpc-cni is also a requirement for the AWS NLB https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/
  # ENABLE_PREFIX_DELEGATION = assign multiple IP addresses from a large IP address block to a network interface
  # ENABLE_POD_ENI = enables Pod Elastic Network Interface, allows to assign ENI to a Pod for network traffic isolution
  # POD_SECURITY_GROU_ENFORCING_MODE = standard = security group specified in the pod annotation withh be enforced
  # enableNetworkPolicy = allows to control traffic flow at IP address and Poert level
  configurationValues:  "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"},\"enableNetworkPolicy\": \"true\"}"
  # This config overwrites any previous config
  resolveConflicts: overwrite

managedNodeGroups:
- name: default
  desiredCapacity: 3
  minSize: 3
  maxSize: 6
  # instanceType: m5.large
  # t2.micro is sufficient for amazonmq -> testing for artemis...
  # instanceType: t2.micro
  # instanceType: t3.micro # -> This led to this error: Warning  Unsupported  2m40s (x22 over 67m)  vpc-resource-controller  The instance type t3.micro is not supported for trunk interface (Security Group for Pods)
  instanceType: m5.large
  # Originally this was set to true
  # Reference found with this video: https://www.youtube.com/watch?v=a4qdvu5cVIU
  # And via querying in bing chat.
  privateNetworking: false
  releaseVersion: 1.27.3-20230816
  updateConfig:
    # maximum percentage of nodes that can be unavailable during an update
    maxUnavailablePercentage: 50
  # -------------------------------------------
  # Removed from eksworkshop config
  # the kubernetes labels to be applied to the nodes in the node group
  # labels:
  #   workshop-default: 'yes'
  # -------------------------------------------
  iam:
    withAddonPolicies:
      # See this: https://github.com/kubernetes-sigs/external-dns
      # This is not required, it was just interesting to experiment with this
      externalDNS: true
      certManager: true
      # Replaces the following commands (during setup, see nodes):
      # `curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.4/docs/install/iam_policy.json`
      # `aws iam create-policy \
      #       --policy-name AWSLoadBalancerControllerIAMPolicy \
      #       --policy-document file://iam_policy.json`
      # This does not work for some reason - https://eksctl.io/usage/iam-policies/
      # No Idea why :(
      awsLoadBalancerController: true
