apiVersion: v1
kind: Service
metadata:
  name: webconsole-nlb-tls
  namespace: activemq-artemis-operator
  annotations:
    # external = explicitly requires an NLB, instead of an ALB
    service.beta.kubernetes.io/aws-load-balancer-type: external
    # ip = route traffic directly to the pod IP
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    # internet-facing = An internet-facing load balancer has a publicly resolvable DNS name
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    # identifies the TLS certificate used by the NLB
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:185309785115:certificate/7610ed7d-5a81-4ea2-a18a-7ba1606cca3e"
    # 443 = determines the port the NLB should listen for TLS traffic on
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "8161"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 8161
    targetPort: 8161
    name: tcp
    protocol: TCP
  selector:
    app: artemis-broker-webconsole-0-svc
  type: LoadBalancer
